// styles/OTPVerificationPopup.styles.ts
import { StyleSheet } from 'react-native';
import { MedicalTheme } from '@/newConstants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: MedicalTheme.colors.background.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MedicalTheme.spacing[6],
    paddingTop: MedicalTheme.spacing[16],
    paddingBottom: MedicalTheme.spacing[5],
    borderBottomWidth: 1,
    borderBottomColor: MedicalTheme.colors.border.light,
  },
  closeButton: {
    padding: MedicalTheme.spacing[1],
  },
  closeButtonPlaceholder: {
    width: MedicalTheme.spacing[8],
  },
  title: {
    fontSize: MedicalTheme.typography.fontSize['2xl'],
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
    textAlign: 'center',
  },
  content: {
    flex: 1,
  },
  // Top illustration section
  topIllustration: {
    height: '30%',
    backgroundColor: MedicalTheme.colors.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: MedicalTheme.spacing[4],
  },
  illustrationImage: {
    width: '100%',
    height: '80%',
    maxHeight: 200,
  },
  // Card section
  card: {
    flex: 1,
    backgroundColor: MedicalTheme.colors.background.primary,
    borderTopLeftRadius: MedicalTheme.borderRadius['3xl'],
    borderTopRightRadius: MedicalTheme.borderRadius['3xl'],
    marginTop: -MedicalTheme.spacing[5],
    paddingTop: MedicalTheme.spacing[8],
    paddingHorizontal: MedicalTheme.spacing[6],
    paddingBottom: MedicalTheme.spacing[4],
    shadowColor: MedicalTheme.shadow.lg.shadowColor,
    shadowOffset: MedicalTheme.shadow.lg.shadowOffset,
    shadowOpacity: MedicalTheme.shadow.lg.shadowOpacity,
    shadowRadius: MedicalTheme.shadow.lg.shadowRadius,
    elevation: MedicalTheme.shadow.lg.elevation,
  },
  formContainer: {
    flex: 1,
    alignItems: 'center',
  },
  subtitle: {
    fontSize: MedicalTheme.typography.fontSize.lg,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.normal,
    color: MedicalTheme.colors.text.secondary,
    textAlign: 'center',
    marginBottom: MedicalTheme.spacing[2],
    // lineHeight: MedicalTheme.typography.lineHeight.normal,
  },
  emailText: {
    fontSize: MedicalTheme.typography.fontSize.lg,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
    textAlign: 'center',
    marginBottom: MedicalTheme.spacing[8],
    // lineHeight: MedicalTheme.typography.lineHeight.normal,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 320,
    marginBottom: MedicalTheme.spacing[8],
  },
  otpInput: {
    width: MedicalTheme.spacing[12],
    height: MedicalTheme.spacing[12],
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.medium,
    borderRadius: MedicalTheme.borderRadius.md,
    fontSize: MedicalTheme.typography.fontSize.xl,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
    backgroundColor: MedicalTheme.colors.background.primary,
    textAlign: 'center',
  },
  otpInputFilled: {
    borderColor: MedicalTheme.colors.primary[500],
    backgroundColor: MedicalTheme.colors.primary[50],
  },
  inputDisabled: {
    opacity: 0.6,
  },
  button: {
    backgroundColor: MedicalTheme.colors.primary[500],
    paddingVertical: MedicalTheme.spacing[4],
    paddingHorizontal: MedicalTheme.spacing[8],
    borderRadius: MedicalTheme.borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 200,
    marginBottom: MedicalTheme.spacing[6],
    minHeight: MedicalTheme.accessibility.minTouchTarget,
    shadowColor: MedicalTheme.shadow.md.shadowColor,
    shadowOffset: MedicalTheme.shadow.md.shadowOffset,
    shadowOpacity: MedicalTheme.shadow.md.shadowOpacity,
    shadowRadius: MedicalTheme.shadow.md.shadowRadius,
    elevation: MedicalTheme.shadow.md.elevation,
  },
  buttonDisabled: {
    backgroundColor: MedicalTheme.colors.primary[200],
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    fontSize: MedicalTheme.typography.fontSize.md,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.inverse,
    textAlign: 'center',
  },
  resendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: MedicalTheme.spacing[8],
  },
  resendText: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.normal,
    color: MedicalTheme.colors.text.secondary,
    textAlign: 'center',
  },
  resendLink: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.primary[500],
    textAlign: 'center',
  },
  resendLinkDisabled: {
    color: MedicalTheme.colors.text.disabled,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingVertical: MedicalTheme.spacing[4],
    borderTopWidth: 1,
    borderTopColor: MedicalTheme.colors.border.light,
  },
  footerText: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.normal,
    color: MedicalTheme.colors.text.secondary,
    textAlign: 'center',
  },
  link: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontFamily: MedicalTheme.typography.fontFamily.primary,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.primary[500],
    textAlign: 'center',
  },
});