import { MedicalTheme } from '@/newConstants/theme';
import { StyleSheet, Platform } from 'react-native';

export const appointmentFormStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: MedicalTheme.spacing[10],
  },
  header: {
    backgroundColor: MedicalTheme.colors.primary[500],
    padding: MedicalTheme.spacing[6],
    paddingTop: Platform.OS === 'ios' ? MedicalTheme.spacing[16] : MedicalTheme.spacing[6],
    borderBottomLeftRadius: MedicalTheme.borderRadius['2xl'],
    borderBottomRightRadius: MedicalTheme.borderRadius['2xl'],
    alignItems: 'center',
    ...MedicalTheme.shadow.lg,
  },
  headerTitle: {
    fontSize: MedicalTheme.typography.fontSize['3xl'],
    fontWeight: MedicalTheme.typography.fontWeight.bold,
    color: MedicalTheme.colors.text.inverse,
    marginTop: MedicalTheme.spacing[3],
  },
  headerSubtitle: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    color: MedicalTheme.colors.text.inverse,
    opacity: 0.9,
    marginTop: MedicalTheme.spacing[1],
  },
  card: {
    backgroundColor: MedicalTheme.colors.background.primary,
    borderRadius: MedicalTheme.borderRadius.xl,
    margin: MedicalTheme.spacing[4],
    marginTop: -MedicalTheme.spacing[5],
    padding: MedicalTheme.spacing[6],
    ...MedicalTheme.shadow.card,
  },
  section: {
    marginBottom: MedicalTheme.spacing[5],
  },
  sectionTitle: {
    fontSize: MedicalTheme.typography.fontSize.lg,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
    marginBottom: MedicalTheme.spacing[4],
    paddingBottom: MedicalTheme.spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: MedicalTheme.colors.border.light,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: MedicalTheme.colors.background.secondary,
    borderRadius: MedicalTheme.borderRadius.lg,
    paddingHorizontal: MedicalTheme.spacing[4],
    paddingVertical: MedicalTheme.spacing[3],
    marginBottom: MedicalTheme.spacing[2],
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.light,
  },
  inputIcon: {
    marginRight: MedicalTheme.spacing[3],
  },
  input: {
    flex: 1,
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.primary,
    paddingVertical: MedicalTheme.spacing[1],
  },
  notesContainer: {
    flexDirection: 'row',
    backgroundColor: MedicalTheme.colors.background.secondary,
    borderRadius: MedicalTheme.borderRadius.lg,
    paddingHorizontal: MedicalTheme.spacing[4],
    paddingVertical: MedicalTheme.spacing[3],
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.light,
  },
  notesInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MedicalTheme.spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: MedicalTheme.colors.border.light,
  },
  settingLabel: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingText: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.primary,
    marginLeft: MedicalTheme.spacing[3],
  },
  expandButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: MedicalTheme.spacing[4],
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: MedicalTheme.colors.border.light,
    marginBottom: MedicalTheme.spacing[2],
  },
  expandButtonText: {
    color: MedicalTheme.colors.primary[500],
    fontWeight: MedicalTheme.typography.fontWeight.medium,
    fontSize: MedicalTheme.typography.fontSize.base,
  },
  additionalFieldsContainer: {
    overflow: 'hidden',
  },
  submitButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: MedicalTheme.colors.primary[500],
    borderRadius: MedicalTheme.borderRadius.lg,
    padding: MedicalTheme.spacing[4],
    marginTop: MedicalTheme.spacing[2],
    ...MedicalTheme.shadow.md,
  },
  submitButtonText: {
    color: MedicalTheme.colors.text.inverse,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    fontSize: MedicalTheme.typography.fontSize.lg,
    marginLeft: MedicalTheme.spacing[3],
  },
  requiredIndicator: {
    color: MedicalTheme.colors.error[500],
    marginLeft: MedicalTheme.spacing[0.5],
  },
  inputLabel: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontWeight: MedicalTheme.typography.fontWeight.medium,
    color: MedicalTheme.colors.text.secondary,
    marginBottom: MedicalTheme.spacing[1],
    marginLeft: MedicalTheme.spacing[1],
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: MedicalTheme.spacing[2],
  },
  dateTimeButton: {
    flex: 1,
    backgroundColor: MedicalTheme.colors.background.secondary,
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.medium,
    borderRadius: MedicalTheme.borderRadius.md,
    paddingVertical: MedicalTheme.spacing[3],
    paddingHorizontal: MedicalTheme.spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: MedicalTheme.spacing[2],
    minHeight: 48,
  },
  dateTimeButtonActive: {
    borderColor: MedicalTheme.colors.primary[500],
    backgroundColor: MedicalTheme.colors.primary[50],
  },
  dateTimeText: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    color: MedicalTheme.colors.text.primary,
    fontWeight: MedicalTheme.typography.fontWeight.medium,
  },
  dateTimeTextActive: {
    color: MedicalTheme.colors.primary[600],
  },
  pickerModal: {
    flex: 1,
    backgroundColor: MedicalTheme.colors.overlay.dark,
    justifyContent: 'flex-end',
    margin: 0,
  },
  pickerContainer: {
    backgroundColor: MedicalTheme.colors.background.primary,
    borderTopLeftRadius: MedicalTheme.borderRadius.xl,
    borderTopRightRadius: MedicalTheme.borderRadius.xl,
    padding: MedicalTheme.spacing[4],
    maxHeight: '50%',
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: MedicalTheme.spacing[4],
    paddingBottom: MedicalTheme.spacing[2],
    borderBottomWidth: 1,
    borderBottomColor: MedicalTheme.colors.border.light,
  },
  pickerTitle: {
    fontSize: MedicalTheme.typography.fontSize.lg,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
  },
  pickerButtonText: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    fontWeight: MedicalTheme.typography.fontWeight.medium,
    color: MedicalTheme.colors.primary[600],
  },
});