import { StyleSheet } from 'react-native';
import { MedicalTheme } from '@/newConstants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: MedicalTheme.colors.background.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: MedicalTheme.spacing[4],
    paddingVertical: MedicalTheme.spacing[3],
    backgroundColor: MedicalTheme.colors.background.primary,
    borderBottomWidth: 1,
    borderBottomColor: MedicalTheme.colors.border.light,
    ...MedicalTheme.shadow.sm,
  },
  backButton: {
    padding: MedicalTheme.spacing[2],
    borderRadius: MedicalTheme.borderRadius.md,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: MedicalTheme.typography.fontSize.xl,
    fontWeight: MedicalTheme.typography.fontWeight.bold,
    color: MedicalTheme.colors.text.primary,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: MedicalTheme.typography.fontSize.xs,
    color: MedicalTheme.colors.text.secondary,
    marginTop: MedicalTheme.spacing[0.5],
    textAlign: 'center',
  },
  headerPlaceholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: MedicalTheme.spacing[4],
    paddingBottom: MedicalTheme.spacing[8],
  },
  introSection: {
    alignItems: 'center',
    marginBottom: MedicalTheme.spacing[6],
    paddingBottom: MedicalTheme.spacing[6],
    borderBottomWidth: 2,
    borderBottomColor: MedicalTheme.colors.secondary[100],
  },
  introIconContainer: {
    width: 80,
    height: 80,
    borderRadius: MedicalTheme.borderRadius.full,
    backgroundColor: MedicalTheme.colors.secondary[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: MedicalTheme.spacing[4],
  },
  introTitle: {
    fontSize: MedicalTheme.typography.fontSize['3xl'],
    fontWeight: MedicalTheme.typography.fontWeight.bold,
    color: MedicalTheme.colors.text.primary,
    marginBottom: MedicalTheme.spacing[2],
    textAlign: 'center',
  },
  introSubtitle: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.secondary,
    marginBottom: MedicalTheme.spacing[3],
    textAlign: 'center',
  },
  introDivider: {
    width: 60,
    height: 3,
    backgroundColor: MedicalTheme.colors.secondary[500],
    borderRadius: MedicalTheme.borderRadius.full,
    marginBottom: MedicalTheme.spacing[3],
  },
  lastUpdated: {
    fontSize: MedicalTheme.typography.fontSize.sm,
    color: MedicalTheme.colors.text.tertiary,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  introductionSection: {
    backgroundColor: MedicalTheme.colors.secondary[50],
    padding: MedicalTheme.spacing[4],
    borderRadius: MedicalTheme.borderRadius.lg,
    marginBottom: MedicalTheme.spacing[6],
    borderLeftWidth: 4,
    borderLeftColor: MedicalTheme.colors.secondary[500],
  },
  introductionText: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.primary,
    lineHeight: MedicalTheme.typography.fontSize.base * MedicalTheme.typography.lineHeight.relaxed,
    marginBottom: MedicalTheme.spacing[3],
  },
  section: {
    marginBottom: MedicalTheme.spacing[6],
    backgroundColor: MedicalTheme.colors.background.primary,
    padding: MedicalTheme.spacing[4],
    borderRadius: MedicalTheme.borderRadius.lg,
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.light,
    ...MedicalTheme.shadow.sm,
  },
  sectionTitle: {
    fontSize: MedicalTheme.typography.fontSize.xl,
    fontWeight: MedicalTheme.typography.fontWeight.bold,
    color: MedicalTheme.colors.secondary[700],
    marginBottom: MedicalTheme.spacing[3],
    lineHeight: MedicalTheme.typography.fontSize.xl * MedicalTheme.typography.lineHeight.tight,
  },
  sectionContent: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.primary,
    lineHeight: MedicalTheme.typography.fontSize.base * MedicalTheme.typography.lineHeight.relaxed,
  },
  acknowledgmentSection: {
    marginTop: MedicalTheme.spacing[6],
    marginBottom: MedicalTheme.spacing[4],
  },
  acknowledgmentCard: {
    backgroundColor: MedicalTheme.colors.primary[50],
    padding: MedicalTheme.spacing[5],
    borderRadius: MedicalTheme.borderRadius.xl,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: MedicalTheme.colors.primary[200],
    ...MedicalTheme.shadow.md,
  },
  acknowledgmentTitle: {
    fontSize: MedicalTheme.typography.fontSize.xl,
    fontWeight: MedicalTheme.typography.fontWeight.bold,
    color: MedicalTheme.colors.primary[700],
    marginTop: MedicalTheme.spacing[3],
    marginBottom: MedicalTheme.spacing[2],
    textAlign: 'center',
  },
  acknowledgmentText: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.primary[800],
    lineHeight: MedicalTheme.typography.fontSize.base * MedicalTheme.typography.lineHeight.relaxed,
    textAlign: 'center',
  },
  footerSection: {
    marginTop: MedicalTheme.spacing[6],
    padding: MedicalTheme.spacing[5],
    backgroundColor: MedicalTheme.colors.neutral[50],
    borderRadius: MedicalTheme.borderRadius.lg,
    borderWidth: 1,
    borderColor: MedicalTheme.colors.border.light,
  },
  footerTitle: {
    fontSize: MedicalTheme.typography.fontSize.lg,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.text.primary,
    marginBottom: MedicalTheme.spacing[2],
    textAlign: 'center',
  },
  footerText: {
    fontSize: MedicalTheme.typography.fontSize.base,
    color: MedicalTheme.colors.text.secondary,
    lineHeight: MedicalTheme.typography.fontSize.base * MedicalTheme.typography.lineHeight.relaxed,
    marginBottom: MedicalTheme.spacing[2],
    textAlign: 'center',
  },
  footerContact: {
    fontSize: MedicalTheme.typography.fontSize.base,
    fontWeight: MedicalTheme.typography.fontWeight.semibold,
    color: MedicalTheme.colors.secondary[600],
    textAlign: 'center',
    marginTop: MedicalTheme.spacing[2],
  },
});

